# Resolve react_native_pods.rb with node to allow for hoisting
 def node_require(script)
   # Resolve script with node to allow for hoisting
   require Pod::Executable.execute_command('node', ['-p',
     "require.resolve(
       '#{script}',
       {paths: [process.argv[1]]},
     )", __dir__]).strip
 end

 node_require('react-native/scripts/react_native_pods.rb')
node_require('react-native-permissions/scripts/setup.rb')
platform :ios, '15.1'
prepare_react_native_project!

setup_permissions([
  'Camera',
  'LocationAccuracy',
  'LocationAlways',
  'LocationWhenInUse'
])

linkage = ENV['USE_FRAMEWORKS']
if linkage != nil
  Pod::UI.puts "Configuring Pod with #{linkage}ally linked Frameworks".green
  use_frameworks! :linkage => linkage.to_sym
end

# ✅ extra pods
pod 'react-native-geolocation-service', :path => '../node_modules/react-native-geolocation-service'
pod 'RCT-Folly', :podspec => '../node_modules/react-native/third-party-podspecs/RCT-Folly.podspec'

target 'korpiein' do
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    :hermes_enabled => true,       # pastikan Hermes aktif
    :new_arch_enabled => false,
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )
  
  post_install do |installer|
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false,
    )

    # ✅ Fix folly Coroutine.h issue
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings["GCC_PREPROCESSOR_DEFINITIONS"] ||= ['$(inherited)']
        config.build_settings["GCC_PREPROCESSOR_DEFINITIONS"] << 'FOLLY_NO_COROUTINES=1'
        config.build_settings["DEBUG_INFORMATION_FORMAT"] = "dwarf-with-dsym"
      end
    end

    # ✅ Generate Hermes dSYM agar tidak error UUID
    begin
      Pod::UI.puts "Generating Hermes dSYMs..."
      system("RCT_NO_LTO=1 #{config[:reactNativePath]}/../node_modules/react-native/scripts/generate-hermes-dsym.sh")
    rescue => e
      Pod::UI.warn "Hermes dSYM generation failed: #{e}"
    end
  end
end
